# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
GMAIL_USERNAME: "AKIAJLWC3F6INL5BKOCQ"
GMAIL_PASSWORD: "AkfugHWTu69yZyzJago4P4nGqjWSRExLBYmHtppa2PO+"
ADMIN_NAME: First User
ADMIN_EMAIL: user@example.com
ADMIN_PASSWORD: 1234qwer
ROLES: [admin, free, paid, paid2]
STRIPE_API_KEY: "sk_test_qUfVi1KXqTvYd6HkjMmjypGH"
STRIPE_PUBLIC_KEY: "pk_test_HPXDBoB6Mpx2Rpkte2WoUad0"

META_KEYWORDS: "Tudli,Make free checklist, To Do Lists"
META_DESCRIPTION: "Make free checklist and To Do Lists for anything and everything you do in the world"
AWS_ACCESS_KEY_ID: AKIAIGBEVLRRFXUUNFGQ
AWS_SECRET_ACCESS_KEY: 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

